### ISSUE TITLE
The game crashes when a province is selected

### ISSUE THREAD

**Issue by nastyasalways** [vawser/warcraft_universalis#3]
Clicking a province will make the game crash. I've tested this using both a custom nation in Northrend and the Quel'Thalas nation in Silvermoon. The only tangible difference is that the "Europa Universalis IV has stopped working" screen comes up after a while in the first case, and instantly in the second. No idea why.

I tried setting the culture and religion to something other than noreligion and noculture (in Silvermoon), to no avail. Changing the primary_culture and religion parts of the Quel'Thalas country history file did nothing, either, except make the game stop functioning *faster* for whatever reason.

**Comment by vawser** [comment]
Was due to the continents.txt not containing any province IDs. I've added the whole range (1-4096) to the europe (EK) continent for now, I will distribute them properly once the map is done.

**Comment by nastyasalways** [comment]
Ah, wonderful!
