### ISSUE TITLE
Full basic history for provinces

### ISSUE THREAD

**Issue by Xanaa** [vawser/warcraft_universalis#42]
Issue will be updated in progres:

(wip) - something is done, but need more fixes

# Eastern Kingdoms
- [x] Quel'Danas
- [x] Eversong Woods
- [x] Ghostlands
- [x] Eastern Plaguelands
- [x] Western Plaguelands
- [x] Tirisfal Glades
- [x] Silverpine Forest
- [x] Hillsbrad Foothills
- [x] The Hinterlands
- [x] Gilneas
- [x] Tol Barad
- [x] Arathi Highlands
- [x] Kul Tiras
- [x] Wetlands
- [x] Twilight Highlands
- [x] Dun Morogh
- [x] Loch Modan
- [x] Searing Gorge
- [x] Badlands
- [x] Burning Steppes
- [x] Stormwind
- [x] Elwynn Forest
- [x] Redridge Mountains
- [x] Westfall
- [x] Duskwood
- [x] Deadwind Pass
- [x] Swamp of Sorrows
- [x] Stranglethorn Vale
- [x] Blasted Lands
- [x] Zul'Dare

# Kalimdor
- [x] Moonglade
- [x] Teldrassil (wip)
- [x] Bloodmyst Isle
- [x] Azuremyst Isle
- [x] Darkshore
- [x] Felwood
- [x] Winterspring
- [x] Mount Hyjal
- [x] Azshara (wip)
- [x] Ashenvale
- [x] Stonetalon Mountains
- [x] Northern Barrens
- [x] Southern Barrens
- [x] Durotar
- [x] Desolace (wip)
- [x] Mulgore (wip)
- [x] Dustwallow Marsh
- [x] Feralas
- [x] Thousand Needles
- [x] Silithus
- [x] Un'goro Crater
- [x] Tanaris
- [x] Ahn'Qiraj (wip)
- [x] Uldum

# Outlands
- [x] Hellfire Peninsula
- [x] Zangarmarsh
- [x] Terokkar Forest (wip)
- [x] Nagrand
- [x] Shadowmoon Valley (wip)
- [x] Blade's Edge Mountains
- [x] Netherstorm

# Northrend
- [x] Borean Tundra
- [x] Dragonblight
- [x] Howling Fjord
- [x] Grizzly Hills
- [x] Wintergrasp
- [x] Sholazar Basin
- [x] Crystalsong Forest
- [x] Zul'Drak
- [x] Icecrown
- [x] Storm Peaks

# Pandaria
- [x] Krasarang Wilds
- [x] Valley of the Four Winds
- [x] The Jade Forest
- [x] Dread Wastes
- [x] Vale of Eternal Blossoms
- [x] Hidden Valley
- [x] Kun-Lai Summit
- [x] Isle of Thunder

# Others
- [x] Lost Isles (need some work)

**Comment by Xanaa** [comment]
Dustwallow Marsh done in 9a029003905a7a6c4d753c8dc99b97906f8a0db6

**Comment by Xanaa** [comment]
Tanaris done in 12bf678e2eb0444336b383a459f60268c46d7fa9

**Comment by Xanaa** [comment]
Silithus done in 2189c7f19ac59dd1bca2076a6da667fd2d7b2ce8

**Comment by Blanchard33** [comment]
Outlands done
