### ISSUE TITLE
Terra Incognita error

### ISSUE THREAD

**Issue by Xanaa** [vawser/warcraft_universalis#55]
http://www.eu4wiki.com/Patch_1.15
In patch 1.15 for Europa Universalis we have new system of exploration:

"Reworked spread of discoveries, instead of spreading on a per province basis, discoveries are now spread in whole regions according to a system fully controlled through scripting"

We need to implement this!

**Comment by vawser** [comment]
I've implemented this in my copy. I've also added suitable areas for the seas so the Exploration mechanic will work correctly.

**Comment by vawser** [comment]
Fixed in @7dbf4d7cf15c54fcdd7a8788c17fdb46bbb0e6f3
